[package]
name = "making-illegal-states-unrepresentable"
version = "0.1"
lean_version = "leanprover-community/lean:3.20.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "253b120d59045b6eaec35781711be1d756f02fb3"}
